language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 5m bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: fKqdVg+xkMfsCvY5qzS1pb82C+P68p4sNa3Zzg9wngA4mPRpKw75WJwDZKRjpnpYPy2uitNr6bLUgaXnuiA8+QizdUX645W3p+tHWiI1x5V4EJTc86bTSsQBETmn4TjoRd0+r4PL1WWu9KBZm1/tvXkEgaUxPc0KIQ9WAqyTiGP2LMpL8v9tFTB9a2zmyp75rQzvcCnfRAPhD8TcPovJyrF07s1HN3TZDdQ7KMGiouK2i2cUAbo4pNvM4hbZaQpx0XLcwF5xYwLOQbrzdkmExbQ/kTB6NKLNtojNSlV42spRoGXZo6Wmm0bwAL2TUuSIowj8fxR7GlV2/HjldCv9/ksuCgeAgpRrJLUXxmFsGXkp9nHGqhIjXtPSDERxQRHQK3hgLwpzPytE1HpRl7yFMxqeZgR1hNHxG8YVBeIeumBegKy3eg/LJENUybt3k4/0yQRk9RMmNadVUXiA+gK/G4SXahAUkEO5yTbUe4cLrHBwj9Qk8PQWOdX/YCJW39mFIyTSQEvhxQ1Ln1QOoBaTpHe3v6FS7QLlLj4C2jIqU7d+moB/vxPimBgg8hlWpgPxJlctLh4pSUk4PRwoFXmOwA67i46A1zSaDT+EY2xgSW2bg3F3d4Z6YKlwrEAaq8Sq+laakAdbrZfTxm7PlQ3iBwpPjLUQLKkjPdPAaukgrhI=
    on_success: always
