---
# Program/Department Title
title: English
# Subdirectory (with / at only at beginning)
baseurl: /english
# Production domain (without / at the end)
production: https://www.cla.temple.edu
# url spits sitemap
url: https://www.cla.temple.edu/english

# Development Config
# If you do not have access to 'tutheme', use 'minima' instead.
theme: tutheme
palette: light #future feature


# Program Information
# Short tagline for tweets (<100 characters)
tagline: This is our life's work
# Longer descriptions for link previews (<250 characters)
description: 'The Department of English teaches students to read and write with clarity, precision and imagination by exploring linguistic practices and literary traditions in Britain, the United States and the English speaking world — with added attention to film, video and photography.'
# List of related keywords for search engines
keywords: highered, college, university, philadelphia, Temple

# Address
address:
  building: Anderson Hall
  room: 1030
  street: 1114 Polett Walk
  city: Philadelphia, PA 19122
  email: english@temple.edu
  phone: 215-204-7561
  
  # University & College Information
university:
  name: Temple University
  url: https://temple.edu/
college:
  name: College of Liberal Arts
  url: https://liberalarts.temple.edu/
program_news: https://liberalarts.temple.edu/news/english
program_events: https://events.temple.edu/department/english


# CSV/JSON/YAML data feeds URLs, to be fetched before each build
events-feed: https://liberalarts.temple.edu/events/english/csv
news-feed: https://liberalarts.temple.edu/news/english/csv
articles-feed: https://liberalarts.temple.edu/articles/english/csv
faculty-feed: https://liberalarts.temple.edu/profiles/english/csv
media-mentions-feed: https://liberalarts.temple.edu/media-mentions/english/csv


# Social Media
# Put in only the username unless otherwise noted
# If social media does not apply to your department, keep it blank or use the default values.
social:
  # Facebook - https://www.facebook.com/USERNAME
  # if your page does not have a custom URL, create one!
  facebook: EnglishAtTemple
  # Twitter - https://twitter.com/USERNAME
  twitter: 
  # Instagram - https://www.instagram.com/USERNAME
  instagram: TULiberalArts
  # Snapchat - USERNAME
  snapchat:
  # GitHub - https://github.com/USERNAME or https://github.com/USERNAME/REPO
  github:
  # DeviantArt - http://USERNAME.deviantart.com/
  deviantart:
  # Vimeo - https://vimeo.com/USERNAME
  vimeo:
  # YouTube - Paste the FULL URL below
  youtube:
  # LinkedIn - Paste the FULL URL below
  linkedin:
  # Slack - Paste the FULL URL below
  slack:
  # Google Tag Manager OR Google Analytics
  google_analytics:
  google_tag_manager: GTM-58ZL5B


# Global Site Config
# DO NOT edit below unless if you know what you're doing!
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
timezone: UTC
collections:
  pages:
    title: Pages
    output: true
    layout: page
permalink: /:title

# Prose
prose:
  rooturl: pages
  media: media
  ignore:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
  - index.html
  - _config.yml
  metadata:
    pages:
      - name: title
        field:
          element: text
          label: Title
      - name: permalink
        field:
          element: text
          label: Permalink
      - name: layout
        field:
          element: select
          label: Page layout
          options:
            - name: page
              value: page
            - name: faculty
              value: faculty
            - name: faculty2
              value: faculty2
            - name: home
              value: home

# Jekyll Ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
  - s3_website.yml
  - .sass-cache
  - .travis.yml
  - .ruby-version
  - .gitignore
  - vendor
  - _site
  - node_modules
